# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import search_pb2 as search__pb2


class TextSearchStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getMessage = channel.unary_unary(
        '/TextSearch.TextSearch/getMessage',
        request_serializer=search__pb2.MessageRequest.SerializeToString,
        response_deserializer=search__pb2.MessageReply.FromString,
        )


class TextSearchServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TextSearchServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getMessage': grpc.unary_unary_rpc_method_handler(
          servicer.getMessage,
          request_deserializer=search__pb2.MessageRequest.FromString,
          response_serializer=search__pb2.MessageReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TextSearch.TextSearch', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
